/* APLUS P6 English Prelim — Online PSLE-style Paper 2 engine */
(function(){
'use strict';
const KEY='APLUS_P6_PRELIM_SESSION_V1';
const TOTAL_TIME=110*60;
const blueprint=[
 {id:'grammar',booklet:'BOOKLET A',name:'GRAMMAR',count:10,marks:10},
 {id:'vocabulary',booklet:'BOOKLET A',name:'VOCABULARY',count:5,marks:5},
 {id:'vocabularyCloze',booklet:'BOOKLET A',name:'VOCABULARY CLOZE',count:5,marks:5},
 {id:'visual',booklet:'BOOKLET A',name:'VISUAL TEXT COMPREHENSION',count:5,marks:5},
 {id:'grammarCloze',booklet:'BOOKLET B',name:'GRAMMAR CLOZE',count:10,marks:10},
 {id:'editing',booklet:'BOOKLET B',name:'EDITING FOR SPELLING AND GRAMMAR',count:10,marks:10},
 {id:'comprehensionCloze',booklet:'BOOKLET B',name:'COMPREHENSION CLOZE',count:15,marks:15},
 {id:'synthesis',booklet:'BOOKLET B',name:'SYNTHESIS / TRANSFORMATION',count:5,marks:10},
 {id:'comprehension',booklet:'BOOKLET B',name:'COMPREHENSION',count:10,marks:20}
];
const $=id=>document.getElementById(id);
const state={questions:[],answers:{},current:0,remaining:TOTAL_TIME,started:false,submitted:false,review:false,seed:Date.now(),candidate:'',klass:''};
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function shuffle(a,r){a=[...a];for(let i=a.length-1;i>0;i--){let j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function rng(seed){let t=seed>>>0;return()=>{t+=0x6D2B79F5;let x=t;x=Math.imul(x^x>>>15,x|1);x^=x+Math.imul(x^x>>>7,x|61);return((x^x>>>14)>>>0)/4294967296}}
function bank(name){return Array.isArray(window[name])?window[name]:[]}
function genericGrammar(r){return bank('APLUS_AI_DB_V1_P6_PSLE_PAPER2_CORE_GRAMMAR_BATCH01').map(x=>({section:'grammar',type:'mcq',marks:1,question:x.context||x.question||x.prompt||x.rule,options:shuffle([x.answer,...(x.distractors||x.options||[]).slice(0,3)],r),answer:x.answer,explanation:x.rule||x.explanation||'',skill:x.skill||x.concept||'Grammar',difficulty:x.difficulty||3}));}
function genericVocab(r){return bank('APLUS_AI_DB_V1_P6_PSLE_PAPER2_CORE_VOCABULARY_BATCH02').map(x=>({section:'vocabulary',type:'mcq',marks:1,question:(x.contextClue||'Choose the word that best matches the meaning in context.')+' Which word is most suitable?',options:shuffle([x.word,...(x.synonyms||[]).slice(0,1),'careless','uncertain'],r),answer:x.word,explanation:x.definition||'',skill:'Vocabulary in context',difficulty:x.difficulty||3}));}
function genericCloze(r){return bank('APLUS_AI_DB_V1_P6_PSLE_PAPER2_CORE_VOCABULARY_CLOZE_DNA_BATCH02').map(x=>({section:'vocabularyCloze',type:'mcq',marks:1,question:x.rule||x.context||x.skill||'Choose the word that best completes the passage.',options:shuffle(x.options||['careful','uncertain','generous','ordinary'],r),answer:x.answer||x.target,explanation:x.distractorRule||'',skill:x.skill||'Vocabulary cloze',difficulty:x.difficulty||3}));}
function makeSeed(section,i,r){
 const seeds={
 visual:[['NOTICE','The school library will close at 4.30 p.m. on Friday for stock-taking. Students should return borrowed books before Thursday.','Why should students return books before Thursday?',['The library will be closed on Friday.','A new library will open on Thursday.','Books cannot be borrowed on Thursday.','Stock-taking starts on Thursday.'],'The library will close on Friday, so books should be returned earlier.'],['POSTER','SAVE WATER. Turn off the tap while brushing your teeth. Report leaking taps to the general office.','Who is the poster mainly addressing?',['Students and staff','Only visitors','Only teachers','Only office workers'],'The instructions are directed to people using school facilities.']],
 grammarCloze:[['After the storm ended, the pupils ___ their classroom because several windows had been left open.',['cleaned','clean','have cleaned','are cleaning'],'cleaned'],['Maya has not ___ her project yet because she is checking the final page.',['finished','finish','finishing','finishes'],'finished'],['The basket of apples ___ on the table near the window.',['is','are','were','have'],'is']],
 editing:[['Each of the boys were asked to bring a water bottle.','were','was','Subject-verb agreement'],['She has went to the office to collect the forms.','went','gone','Present perfect verb form'],['We arrived at the station in Monday morning.','in','on','Preposition of time']],
 comprehensionCloze:[['The class planted seedlings in a corner of the school garden. At first, the soil was dry, so the pupils watered it regularly. After several weeks, the first leaves appeared. The pupils were delighted because their careful effort had finally produced a result.','The word "delighted" most nearly means',['pleased','worried','confused','angry'],'pleased'],['A rainstorm damaged the community garden. Instead of giving up, the volunteers repaired the beds and replanted the vegetables. A month later, the garden was growing again.','Why did the garden recover?',['The volunteers repaired and replanted it.','The storm became stronger.','The vegetables were removed.','The garden was abandoned.'],'The volunteers repaired and replanted it.']],
 synthesis:[['The box was so heavy that Ali could not lift it.','too...to','The box was too heavy for Ali to lift.'],['Although it was raining, the pupils continued the activity.','despite','Despite the rain, the pupils continued the activity.'],['Because the road was flooded, the bus was delayed.','because of','Because of the flooded road, the bus was delayed.']],
 comprehension:[['The old footbridge had become slippery after several days of rain. The pupils were told to use another route while the school arranged repairs.','What was the main reason pupils had to use another route?',['The bridge was unsafe.','The route was shorter.','The school had moved.','The bridge was new.'],'The bridge had become slippery and unsafe.'],['Jia found a sketchbook on a bench. She wanted to keep it, but she noticed the owner had written a name on the first page. She handed it to the office instead.','What does Jia\'s action show about her?',['She is honest and considerate.','She is careless.','She is impatient.','She is secretive.'],'She chose to return the item after finding the owner\'s name.']]
 };
 const a=seeds[section]||[];const z=a[i%a.length];
 if(section==='editing')return{section,type:'editing',marks:1,question:z[0],original:z[1],answer:z[2],options:[z[2],z[1]],explanation:z[3],skill:z[3],difficulty:3};
 if(section==='synthesis')return{section,type:'text',marks:2,question:z[0]+' Rewrite the sentence beginning with the given idea.\nRequired structure: '+z[1],answer:z[2],acceptedPatterns:[z[2]],explanation:'Meaning and required structure must be preserved.',skill:z[1],difficulty:3};
 return{section,type:'mcq',marks:1,question:z[1],passage:z[0],options:shuffle(z[2],r),answer:z[3],explanation:'Use the evidence and meaning in the text.',skill:section,difficulty:3};
}
function buildExam(){const r=rng(state.seed);let qs=[];for(const b of blueprint){let pool=[];if(b.id==='grammar')pool=genericGrammar(r);if(b.id==='vocabulary')pool=genericVocab(r);if(b.id==='vocabularyCloze')pool=genericCloze(r);if(b.id==='grammarCloze')pool=bank('APLUS_AI_DB_V1_P6_PSLE_PAPER2_CORE_GRAMMAR_CLOZE_DNA_BATCH02').map(x=>({section:b.id,type:'mcq',marks:1,question:x.rule||x.constraint||x.skill,options:shuffle(x.options||['was','were','has','have'],r),answer:x.answer,explanation:x.misconception||'',skill:x.skill||'Grammar cloze',difficulty:x.difficulty||3}));if(b.id==='editing')pool=bank('APLUS_AI_DB_V1_P6_PSLE_PAPER2_CORE_EDITING_DNA_BATCH02').map(x=>({section:b.id,type:'editing',marks:1,question:x.original,original:x.original,answer:x.correct,options:[x.correct,x.original],explanation:x.rule||'',skill:x.errorType||'Editing',difficulty:x.difficulty||3}));if(b.id==='visual'||b.id==='comprehensionCloze'||b.id==='synthesis'||b.id==='comprehension')pool=[];for(let i=0;i<b.count;i++){if(pool.length)qs.push({...pool[i%pool.length],id:'Q'+(qs.length+1),sectionName:b.name});else qs.push({...makeSeed(b.id,i,r),id:'Q'+(qs.length+1),sectionName:b.name,section:b.id});}}
 state.questions=qs;state.answers={};state.current=0;state.remaining=TOTAL_TIME;state.submitted=false;state.review=false;save();}
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(id).classList.add('active')}
function start(resume){if(resume){const s=JSON.parse(localStorage.getItem(KEY));Object.assign(state,s);state.started=true;}else{state.candidate=$('candidateName').value.trim()||'Candidate';state.klass=$('candidateClass').value.trim();state.seed=Date.now();buildExam();state.started=true;save()}show('exam');render();}
function save(){if(state.started&&!state.submitted)localStorage.setItem(KEY,JSON.stringify(state));}
function render(){const q=state.questions[state.current],b=blueprint.find(x=>x.id===q.section)||blueprint[0];$('bookletLabel').textContent=b.booklet;$('sectionLabel').textContent=q.sectionName;$('progressText').textContent=`Question ${state.current+1} of ${state.questions.length}`;$('markText').textContent=`${q.marks} mark${q.marks>1?'s':''}`;$('progressBar').style.width=((state.current+1)/state.questions.length*100)+'%';renderNav();let body=`<div class="section-heading">${esc(q.sectionName)}</div><div class="question-number">Question ${state.current+1}</div>`;if(q.passage)body+=`<div class="passage">${esc(q.passage)}</div>`;body+=`<div class="question-text">${esc(q.question||'')}</div>`;
 if(q.type==='editing')body+=`<input class="answer-input" data-input value="${esc(state.answers[q.id]||'')}" placeholder="Enter the corrected word">`;
 else if(q.type==='text')body+=`<textarea class="answer-input short-answer" data-input placeholder="Type your answer here">${esc(state.answers[q.id]||'')}</textarea>`;
 else body+=`<div class="options">${(q.options||[]).map((o,i)=>`<button class="option ${(state.answers[q.id]===o?'selected':'')}" data-option="${esc(o)}">${String.fromCharCode(65+i)}. ${esc(o)}</button>`).join('')}</div>`;
 if(state.review)body+=`<div class="review-note"><strong>Answer:</strong> ${esc(q.answer||'')}<br><strong>Explanation:</strong> ${esc(q.explanation||'')}</div>`;$('questionCard').innerHTML=body;$('prevBtn').disabled=state.current===0;$('nextBtn').textContent=state.current===state.questions.length-1?'FINISH PAPER':'Next';if(state.review){$('nextBtn').style.display='none';$('prevBtn').textContent=state.current===0?'BACK TO RESULT':'Previous';}}
function renderNav(){let html='';for(const b of blueprint){html+=`<div class="section-block"><div class="section-name">${esc(b.name)}</div><div class="nav-questions">`;let start=blueprint.slice(0,blueprint.indexOf(b)).reduce((n,x)=>n+x.count,0);for(let i=0;i<b.count;i++){let n=start+i,cl=(n===state.current?'current ':'')+(state.answers[state.questions[n]?.id]!==undefined?'answered':'');html+=`<button class="qnav ${cl}" data-nav="${n}">${n+1}</button>`}html+='</div></div>'}$('sectionNav').innerHTML=html;}
function answer(v){state.answers[state.questions[state.current].id]=v;save();render()}
function tick(){if(!state.started||state.submitted)return;state.remaining=Math.max(0,state.remaining-1);let h=Math.floor(state.remaining/3600),m=Math.floor(state.remaining%3600/60),s=state.remaining%60;$('timer').textContent=`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;if(state.remaining===0)prepareSubmit(true);if(state.remaining%10===0)save()}
function prepareSubmit(auto){const answered=Object.keys(state.answers).length;let marks=state.questions.reduce((n,q)=>n+(state.answers[q.id]!==undefined&&String(state.answers[q.id]).trim()!==''?q.marks:0),0);$('submitSummary').innerHTML=`<strong>${state.questions.length} questions</strong><br>${answered} answered · ${state.questions.length-answered} unanswered · ${marks} marks attempted${auto?'<br><br><strong>Time has expired. The paper is ready for submission.</strong>':''}`;show('submitScreen')}
function submit(){state.submitted=true;localStorage.removeItem(KEY);showResult();}
function showResult(){let earned=0;const by={};state.questions.forEach(q=>{const ok=String(state.answers[q.id]??'').trim().toLowerCase()===String(q.answer??'').trim().toLowerCase();if(ok)earned+=q.marks;by[q.section]=(by[q.section]||{earned:0,total:0,name:q.sectionName});by[q.section].total+=q.marks;if(ok)by[q.section].earned+=q.marks});let pct=Math.round(earned/90*100);$('score').textContent=`${earned} / 90`;$('percentage').textContent=pct+'%';$('resultMessage').textContent=pct>=80?'Strong progress — review the questions you missed and keep building consistency.':pct>=50?'More practice will help strengthen accuracy and transfer.':'Let’s rebuild the basics and work through targeted practice.';$('sectionResults').innerHTML=Object.values(by).map(x=>`<div class="section-result"><span>${esc(x.name)}</span><strong>${x.earned}/${x.total}</strong></div>`).join('');show('result');}
$('startBtn').onclick=()=>start(false);$('resumeBtn').onclick=()=>start(true);$('nextBtn').onclick=()=>{if(state.review)return;if(state.current===state.questions.length-1)prepareSubmit(false);else{state.current++;save();render()}};$('prevBtn').onclick=()=>{if(state.review&&state.current===0){showResult();return}if(state.current>0){state.current--;render()}};$('confirmSubmitBtn').onclick=submit;$('backToExamBtn').onclick=()=>{state.review=false;show('exam');render()};$('newExamBtn').onclick=()=>{localStorage.removeItem(KEY);$('candidateName').value='';show('landing');checkResume()};$('reviewBtn').onclick=()=>{state.review=true;state.current=0;show('exam');render()};document.addEventListener('click',e=>{const o=e.target.closest('[data-option]');if(o&&!state.review)answer(o.getAttribute('data-option'));const n=e.target.closest('[data-nav]');if(n&&!state.review){state.current=Number(n.getAttribute('data-nav'));render()}});document.addEventListener('input',e=>{if(e.target.matches('[data-input]')&&!state.review){state.answers[state.questions[state.current].id]=e.target.value;save()}});function checkResume(){if(localStorage.getItem(KEY))$('resumeBtn').classList.remove('hidden');else $('resumeBtn').classList.add('hidden')}checkResume();setInterval(tick,1000);})();
