/* APLUS P6 English Prelim — adaptive PSLE-style Paper 2 engine */
(function(){
'use strict';
const KEY='APLUS_P6_PRELIM_SESSION_V2',COMPLETED='APLUS_P6_PRELIM_COMPLETED_V2',TOTAL_TIME=6600;
const BLUEPRINT=[
{id:'grammar',name:'BOOKLET A · Grammar',count:10,marks:10,booklet:'A'},
{id:'vocabulary',name:'BOOKLET A · Vocabulary',count:5,marks:5,booklet:'A'},
{id:'vocabularyCloze',name:'BOOKLET A · Vocabulary Cloze',count:5,marks:5,booklet:'A'},
{id:'visual',name:'BOOKLET A · Visual Text Comprehension',count:5,marks:5,booklet:'A'},
{id:'grammarCloze',name:'BOOKLET B · Grammar Cloze',count:10,marks:10,booklet:'B'},
{id:'editing',name:'BOOKLET B · Editing for Spelling and Grammar',count:10,marks:10,booklet:'B'},
{id:'comprehensionCloze',name:'BOOKLET B · Comprehension Cloze',count:15,marks:15,booklet:'B'},
{id:'synthesis',name:'BOOKLET B · Synthesis and Transformation',count:5,marks:10,booklet:'B'},
{id:'comprehension',name:'BOOKLET B · Comprehension Open-Ended',count:10,marks:20,booklet:'B'}];
const profiles={standard:{difficulty:[2,4]},hard:{difficulty:[3,5]},vocabularyIntensive:{difficulty:[2,5]},grammarIntensive:{difficulty:[2,5]},comprehensionIntensive:{difficulty:[2,5]},psleSimulation:{difficulty:[2,5]},studentWeakness:{difficulty:[1,4]}};
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=x=>String(x??'').trim().toLowerCase();
function seed(){return Math.floor(100000+Math.random()*899999)}
function rng(a){return()=>{a|=0;a=a+0x6D2B79F5|0;let t=a;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function shuffle(a,r){a=[...a];for(let i=a.length-1;i>0;i--){let j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function db(n){return Array.isArray(window[n])?window[n]:[]}
function uniqueOptions(answer,raw,r){let a=[];for(const x of [answer,...(raw||[])]){if(x!=null&&!a.some(y=>norm(y)===norm(x)))a.push(String(x))}return shuffle(a,r).slice(0,4)}
function mcq(rec,section,r,i){let answer=rec.answer||rec.correct||rec.word||rec.target||'';let q=rec.question||rec.prompt||rec.context||'';let raw=rec.options||rec.distractors||[];if(!q&&rec.definition)q=`Choose the word that best matches this meaning: ${rec.definition}`;let opts=uniqueOptions(answer,raw,r);if(opts.length<4){let extras=['careful','ordinary','uncertain','generous','patient','reliable','suitable','effective'];opts=uniqueOptions(answer,opts.concat(extras),r)}return{id:`${section}-${rec.id||i}`,section,sectionName:'',question:q||'Choose the best answer.',options:opts,answer,marks:1,skill:rec.skill||rec.primarySkill||rec.concept||section,difficulty:rec.difficulty||3,sourceId:rec.id||'',sourceType:'APLUS_DATABASE'} }
const FALLBACK={
visual:[['A school notice says the library will close at 3 p.m. on Friday for cleaning. What should pupils do?',['Return borrowed books before closing','Stay in the library until 5 p.m.','Bring sports equipment','Attend a club meeting'],'Return borrowed books before closing','retrieval'],['A poster says “Bring a reusable bottle. Save water. Reduce waste.” Who is the poster mainly addressing?',['People who use the school','Only teachers','Bus drivers','Shop owners'],'People who use the school','audience'],['A timetable shows Art on Monday at 2 p.m. and Science on Tuesday at 3 p.m. When is Science?',['Tuesday at 3 p.m.','Monday at 3 p.m.','Tuesday at 2 p.m.','Wednesday at 3 p.m.'],'Tuesday at 3 p.m.','retrieval'],['A notice changes a bus route because road works are taking place. Why was the route changed?',['Because of road works','Because the bus was full','Because school ended early','Because of heavy homework'],'Because of road works','cause and effect'],['A poster advises pupils to check their work before submitting it. What is the main purpose?',['To encourage careful checking','To advertise a competition','To announce a holiday','To teach a sport'],'To encourage careful checking','purpose']],
comprehensionCloze:[['Mia forgot her umbrella. When dark clouds appeared, her friend offered to share one with her. Mia felt ______ by the kind gesture.',['grateful','ancient','fragile','silent'],'grateful','emotion inference'],['The plants were watered regularly; ______, they grew well.',['therefore','although','unless','instead'],'therefore','cause and effect'],['The path was slippery because it had rained. The pupils walked ______.',['carefully','careful','careless','care'],'carefully','word form'],['The box was too heavy for Ben to carry, so he asked his sister for ______.',['help','helpful','helped','helping'],'help','word form']],
synthesis:[['Tom was very tired. He finished his homework. Combine the sentences using “although”.','Although Tom was very tired, he finished his homework.','although'],['The rain was heavy. The match was cancelled. Combine using “because”.','The match was cancelled because the rain was heavy.','because'],['The bag was too heavy for Sara to lift. Rewrite using “not ... enough”.','The bag was not light enough for Sara to lift.','enough'],['The room was so noisy that I could not concentrate. Rewrite using “too ... to”.','The room was too noisy for me to concentrate.','too to'],['He left early because he wanted to catch the bus. Rewrite using “so that”.','He left early so that he could catch the bus.','purpose']],
editing:[['Neither of the boys were ready for the race.','Neither of the boys was ready for the race.','subject-verb agreement'],['She has went to the library already.','She has gone to the library already.','verb form'],['There are much equipment in the room.','There is much equipment in the room.','uncountable noun'],['We arrived in the station at noon.','We arrived at the station at noon.','preposition'],['He is good in solving difficult puzzles.','He is good at solving difficult puzzles.','preposition']],
grammarCloze:[['By the time we arrived, the film ______.',['had started','starts','will start','is starting'],'had started','past perfect'],['She has not finished her work ______.',['yet','already','ago','last'],'yet','present perfect'],['The pupils ______ their teacher for help when the problem became difficult.',['asked','asking','asks','has ask'],'asked','past tense'],['If it rains tomorrow, we ______ indoors.',['will stay','stayed','would stayed','are stay'],'will stay','first conditional']],
comprehension:[['The old footbridge had become slippery after several days of rain. The pupils were told to use another route while the school arranged repairs. Why did pupils have to use another route?',['The bridge had become unsafe.','The route was shorter.','The school had moved.','The bridge was new.'],'The bridge had become unsafe.','inference'],['Jia found a sketchbook on a bench. She noticed the owner had written a name on the first page. She handed it to the office. What does this show about Jia?',['She is honest and considerate.','She is careless.','She is impatient.','She is secretive.'],'She is honest and considerate.','character inference'],['The community garden produced vegetables and also brought neighbours together. What was its greatest value?',['It helped build relationships.','It replaced the library.','It made everyone wealthy.','It required no work.'],'It helped build relationships.','main idea'],['A pupil failed to grow seeds because the soil was dry. What should she do first?',['Water the soil regularly.','Remove all the seeds.','Stop checking the garden.','Move the seeds indoors forever.'],'Water the soil regularly.','cause and effect'],['A volunteer repaired a bicycle instead of throwing it away. What does this action suggest?',['He values repairing and reusing things.','He dislikes bicycles.','He wanted to waste parts.','He had never seen a bicycle.'],'He values repairing and reusing things.','inference']]};
function fallback(type,i,r){let d=FALLBACK[type]||[];let z=d[i%d.length];if(type==='synthesis')return{id:`fb-${type}-${i}`,section:type,question:z[0],answer:z[1],acceptedPatterns:[z[1]],marks:2,skill:z[2],difficulty:3,type:'text',sourceType:'APLUS_ORIGINAL'};if(type==='editing')return{id:`fb-${type}-${i}`,section:type,question:z[0],answer:z[1],marks:1,skill:z[2],difficulty:3,type:'editing',sourceType:'APLUS_ORIGINAL'};return{id:`fb-${type}-${i}`,section:type,question:z[0],options:shuffle(z[1],r),answer:z[2],marks:1,skill:z[3],difficulty:3,type:'mcq',sourceType:'APLUS_ORIGINAL'} }
function comprehensionPool(){let out=[];for(const p of db('APLUS_AI_DB_V1_P6_COMPREHENSION_PASSAGE_SETS_BATCH02'))for(const q of (p.questions||[]))out.push({...q,passage:p.text,title:p.title,passageId:p.passageId});return out}
function buildQuestions(profile,student,s){let r=rng(s),used=new Set(),qs=[];let pools={grammar:db('APLUS_AI_DB_V1_P6_PSLE_PAPER2_CORE_GRAMMAR_BATCH01'),vocabulary:db('APLUS_AI_DB_V1_P6_PSLE_PAPER2_CORE_VOCABULARY_BATCH02'),vocabularyCloze:db('APLUS_AI_DB_V1_P6_PSLE_PAPER2_CORE_VOCABULARY_CLOZE_DNA_BATCH02'),visual:[],grammarCloze:db('APLUS_AI_DB_V1_P6_PSLE_PAPER2_CORE_GRAMMAR_CLOZE_DNA_BATCH02'),editing:db('APLUS_AI_DB_V1_P6_PSLE_PAPER2_CORE_EDITING_DNA_BATCH02'),comprehensionCloze:db('APLUS_AI_DB_V1_P6_CLOZE_EDITING_EXPANSION_BATCH02').concat(db('APLUS_AI_DB_V1_P6_CLOZE_EDITING_EXPANSION_BATCH04')),synthesis:db('APLUS_AI_DB_V1_P6_SYNTHESIS_TRANSFORMATION_EXPANSION_BATCH02').concat(db('APLUS_AI_DB_V1_P6_SYNTHESIS_TRANSFORMATION_EXPANSION_BATCH04')),comprehension:comprehensionPool()};
BLUEPRINT.forEach(sec=>{for(let i=0;i<sec.count;i++){let pool=pools[sec.id]||[],rec=pool.filter(x=>!used.has(x.id||x.passageId)).sort(()=>r()-.5)[0],q;if(rec){used.add(rec.id||rec.passageId);if(sec.id==='comprehension')q={...rec,section:sec.id,marks:2,type:'mcq',skill:rec.skill||rec.type,difficulty:rec.difficulty||3,sourceId:rec.id,sourceType:'APLUS_DATABASE'};else q=mcq(rec,sec.id,r,i)}else q=fallback(sec.id,i,r);q.number=qs.length+1;q.sectionName=sec.name;q.booklet=sec.booklet;q.marks=sec.id==='synthesis'?2:sec.id==='comprehension'?2:1;q.paperSeed=s;qs.push(q)}});return qs}
function fresh(){return{candidate:'',klass:'',profile:'standard',seed:seed(),paperId:'',questions:[],answers:{},index:0,remaining:TOTAL_TIME,started:false,submitted:false}}
let state=(()=>{try{return JSON.parse(localStorage.getItem(KEY))||fresh()}catch(e){return fresh()}})();
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch(e){}}
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(id)?.classList.add('active')}
function renderNav(){let root=$('sectionNav');root.innerHTML='';BLUEPRINT.forEach(s=>{let w=document.createElement('div');w.className='nav-section';w.innerHTML=`<div class="nav-section-title">${esc(s.name)}</div>`;state.questions.filter(q=>q.section===s.id).forEach(q=>{let b=document.createElement('button');b.className='nav-q'+(q.number-1===state.index?' current':'')+(state.answers[q.id]!=null?' answered':'');b.textContent=q.number;b.onclick=()=>{state.index=q.number-1;save();render()};w.appendChild(b)});root.appendChild(w)})}
function render(){let q=state.questions[state.index];if(!q)return;let sec=BLUEPRINT.find(x=>x.id===q.section);$('bookletLabel').textContent=`BOOKLET ${q.booklet}`;$('sectionLabel').textContent=(sec?.name||q.section).replace(/^BOOKLET [AB] · /,'');$('progressText').textContent=`Question ${q.number} of ${state.questions.length}`;$('progressBar').style.width=`${q.number/state.questions.length*100}%`;$('markText').textContent=`${q.marks} ${q.marks===1?'mark':'marks'}`;let h=`<div class="q-kicker">${esc(q.sectionName)} <span>${q.marks} ${q.marks===1?'mark':'marks'}</span></div><h2>Question ${q.number}</h2>`;if(q.title)h+=`<div class="passage-title"><strong>${esc(q.title)}</strong></div>`;if(q.passage)h+=`<div class="passage">${esc(q.passage)}</div>`;if(q.visual)h+=`<div class="visual"><strong>${esc(q.visual.title||'VISUAL TEXT')}</strong><div>${esc(q.visual.text||'')}</div></div>`;h+=`<div class="question-text">${esc(q.question)}</div>`;if(q.options)h+=`<div class="options">${q.options.map((o,i)=>`<label class="option"><input type="radio" name="answer" value="${esc(o)}" ${norm(state.answers[q.id])===norm(o)?'checked':''}><span>${String.fromCharCode(65+i)}</span><em>${esc(o)}</em></label>`).join('')}</div>`;else h+=`<textarea id="textAnswer" rows="5" placeholder="Type your answer here">${esc(state.answers[q.id]||'')}</textarea>`;$('questionCard').innerHTML=h;document.querySelectorAll('input[name=answer]').forEach(x=>x.onchange=()=>{state.answers[q.id]=x.value;save();renderNav()});$('textAnswer')?.addEventListener('input',e=>{state.answers[q.id]=e.target.value;save()});$('prevBtn').disabled=state.index===0;$('nextBtn').textContent=state.index===state.questions.length-1?'END EXAMINATION':'Next';renderNav();$('timer').textContent=format(state.remaining)}
function format(s){return`${String(Math.floor(s/3600)).padStart(2,'0')}:${String(Math.floor(s%3600/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function start(){state=fresh();state.candidate=$('candidateName').value.trim()||'Candidate';state.klass=$('candidateClass').value.trim();state.profile=$('paperProfile').value;state.paperId=`APLUS-P6-ENG-P2-${new Date().getFullYear()}-${String(state.seed).slice(-6)}`;state.questions=buildQuestions(state.profile,state.student,state.seed);state.started=true;save();show('exam');render()}
function resume(){let x;try{x=JSON.parse(localStorage.getItem(KEY)||'null')}catch(e){}if(x){state=x;show('exam');render()}}
function submit(){state.submitted=true;state.completedAt=new Date().toISOString();state.score=state.questions.reduce((n,q)=>n+(match(q,state.answers[q.id])?q.marks:0),0);state.total=90;localStorage.setItem(COMPLETED,JSON.stringify(state));localStorage.removeItem(KEY);showResult()}
function match(q,u){let a=norm(u);if(q.type==='text'||q.type==='editing')return[q.answer,...(q.acceptedPatterns||[])].map(norm).includes(a);return a===norm(q.answer)}
function showSubmit(){let a=state.questions.filter(q=>state.answers[q.id]!=null&&String(state.answers[q.id]).trim()).length;$('submitSummary').innerHTML=`<div><strong>${a}</strong> of <strong>${state.questions.length}</strong> questions answered</div><div>Paper ID: <strong>${esc(state.paperId)}</strong></div><div>Time remaining: <strong>${format(state.remaining)}</strong></div>`;show('submitScreen')}
function showResult(){let score=state.score||0;$('paperId').textContent=`Paper ID: ${state.paperId}`;$('score').textContent=`${score} / 90`;$('percentage').textContent=`${Math.round(score/90*100)}%`;$('resultMessage').textContent=score>=80?'Strong performance. Review the questions you missed and keep building consistency.':score>=60?'Good progress. Target the weaker skills shown below.':'Use the analysis below to rebuild the skills that need more practice.';let sr={};state.questions.forEach(q=>{let x=sr[q.section]||(sr[q.section]={m:0});if(match(q,state.answers[q.id]))x.m+=q.marks});$('sectionResults').innerHTML='<h3>Section Performance</h3>'+BLUEPRINT.map(s=>{let x=sr[s.id]||{m:0};return`<div class="result-row"><span>${esc(s.name.replace(/^BOOKLET [AB] · /,''))}</span><b>${x.m}/${s.marks}</b></div>`}).join('');let sk={};state.questions.forEach(q=>{let k=q.skill||q.section;sk[k]||(sk[k]={c:0,t:0});sk[k].t++;if(match(q,state.answers[q.id]))sk[k].c++});$('skillResults').innerHTML='<h3>Skill Analysis</h3>'+Object.entries(sk).sort((a,b)=>a[1].c/a[1].t-b[1].c/b[1].t).slice(0,10).map(([k,v])=>`<div class="result-row"><span>${esc(k)}</span><b>${v.c}/${v.t}</b></div>`).join('');show('result')}
function print(){let d=state.questions.length?state:JSON.parse(localStorage.getItem(COMPLETED)||'null');if(!d)return;let w=window.open('','_blank');if(!w)return;let body=BLUEPRINT.map(s=>`<h3>${esc(s.name)}</h3>`+d.questions.filter(q=>q.section===s.id).map(q=>`<div class="q"><b>${q.number}. ${esc(q.question)}</b>${q.passage?`<p>${esc(q.passage)}</p>`:''}${q.options?q.options.map((o,i)=>`<div>${String.fromCharCode(65+i)}. ${esc(o)}</div>`).join(''):`<p class="line">${esc(d.answers[q.id]||'')}</p>`}</div>`).join('')).join('');w.document.write(`<html><head><title>${esc(d.paperId)}</title><style>@page{size:A4;margin:15mm}body{font:12px Arial;line-height:1.5}.brand{text-align:center;font-weight:bold;letter-spacing:3px}.title{text-align:center;font:24px Georgia}.meta{border:1px solid #333;padding:8px;margin:10px 0}.q{break-inside:avoid;margin:0 0 14px}.line{border-bottom:1px solid #555;min-height:24px}.key{page-break-before:always}</style></head><body><div class="brand">APLUS ACHIEVER</div><div class="title">APLUS P6 English Prelim</div><div style="text-align:center">PSLE-Style English Language Examination<br>Paper 2 — Language Use and Comprehension</div><div class="meta">Candidate: ${esc(d.candidate)} &nbsp; Paper ID: ${esc(d.paperId)} &nbsp; Total: 90 marks</div>${body}<div class="key"><h2>Answer Key</h2>${d.questions.map(q=>`<div>${q.number}. ${esc(q.answer||'')}</div>`).join('')}</div></body></html>`);w.document.close();setTimeout(()=>w.print(),400)}
$('startBtn').onclick=start;$('resumeBtn').onclick=resume;$('prevBtn').onclick=()=>{if(state.index>0){state.index--;save();render()}};$('nextBtn').onclick=()=>{if(state.index<state.questions.length-1){state.index++;save();render()}else showSubmit()};$('confirmSubmitBtn').onclick=submit;$('backToExamBtn').onclick=()=>{show('exam');render()};$('reviewBtn').onclick=()=>{state.index=0;show('exam');render()};$('printBtn').onclick=print;$('newExamBtn').onclick=()=>{localStorage.removeItem(COMPLETED);state=fresh();show('landing');$('resumeBtn').classList.add('hidden')};
if(state.started&&!state.submitted){$('resumeBtn').classList.remove('hidden');render()}setInterval(()=>{if(!state.started||state.submitted)return;state.remaining=Math.max(0,state.remaining-1);$('timer').textContent=format(state.remaining);if(state.remaining===0)showSubmit();if(state.remaining%5===0)save()},1000);
window.APLUS_P6_PRELIM_V2={generate:(profile='standard',s=seed())=>buildQuestions(profile,null,s),BLUEPRINT,print,getState:()=>state};
})();