/* APLUS P6 English Prelim — Printable Examination / Answer Key / Teacher Version */
(function(){
'use strict';
function esc(s){return String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));}
function getState(){return window.__APLUS_PRELIM_STATE__||null;}
function page(title,body){const w=window.open('','_blank');if(!w){alert('Please allow pop-ups to print the examination.');return;}w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${esc(title)}</title><style>@page{size:A4;margin:16mm 15mm}*{box-sizing:border-box}body{font-family:Arial,Helvetica,sans-serif;color:#111;margin:0;font-size:12px;line-height:1.5}.page{page-break-after:always}.page:last-child{page-break-after:auto}.brand{text-align:center;font-size:11px;letter-spacing:3px;font-weight:bold;margin-bottom:12px}.title{text-align:center;font-family:Georgia,serif;font-size:25px;margin:0}.subtitle{text-align:center;font-size:14px;margin:5px 0 18px}.meta{border:1px solid #222;padding:9px;margin:14px 0;display:flex;justify-content:space-between}.section{font-weight:bold;font-size:15px;border-bottom:1.5px solid #111;padding:9px 0;margin:18px 0 12px}.q{margin:0 0 15px;break-inside:avoid}.qn{font-weight:bold}.passage{border:1px solid #aaa;padding:12px;margin:9px 0;white-space:pre-wrap}.option{margin:4px 0 4px 18px}.answer{margin-top:7px;border-bottom:1px solid #999;min-height:22px}.answer.filled{border:1px solid #777;padding:5px;min-height:25px}.small{font-size:10px;color:#555}.marks{float:right;font-weight:bold}.visual{border:1px solid #777;padding:16px;margin:9px 0;background:#fafafa}.keytable{width:100%;border-collapse:collapse}.keytable td,.keytable th{border:1px solid #999;padding:6px;text-align:left}.center{text-align:center}.teacher-note{border:1px solid #aaa;padding:10px;margin:8px 0}.pagebreak{page-break-before:always}</style></head><body>${body}</body></html>`);w.document.close();setTimeout(()=>w.print(),400);}
function header(title,sub){return `<div class="brand">APLUS ACHIEVER</div><h1 class="title">APLUS P6 English Prelim</h1><div class="subtitle">${esc(title)}<br>${esc(sub||'PSLE-Style English Language Examination')}</div>`;}
function questionHtml(q,i,withAnswers){let s=`<div class="q"><div><span class="qn">${i+1}. </span>${esc(q.question||'')} <span class="marks">[${q.marks}]</span></div>`;if(q.passage)s+=`<div class="passage">${esc(q.passage)}</div>`;if(q.visual)s+=`<div class="visual"><strong>${esc(q.visual.title||'VISUAL TEXT')}</strong><br>${esc(q.visual.text||'')}</div>`;if(q.options){s+=q.options.map((o,j)=>`<div class="option">${String.fromCharCode(65+j)}. ${esc(o)}</div>`).join('');}if(q.type==='editing')s+=`<div class="answer ${withAnswers?'filled':''}">${withAnswers?esc(q.answer||''):''}</div>`;else if(q.type==='text')s+=`<div class="answer ${withAnswers?'filled':''}">${withAnswers?esc(q.answers||q.answer||''):''}</div>`;return s+'</div>';}
function printPaper(){const st=getState();if(!st||!st.questions?.length){alert('Complete or start an examination first.');return;}let body='';let last='';st.questions.forEach((q,i)=>{if(q.sectionName!==last){body+=`<div class="section">${esc(q.sectionName)} <span class="marks">${q.sectionName}</span></div>`;last=q.sectionName;}body+=questionHtml(q,i,true);});page('APLUS P6 English Prelim — Completed Paper',header('Completed Examination','Paper 2 — Language Use and Comprehension')+`<div class="meta"><span>Candidate: <b>${esc(st.candidate||'Candidate')}</b></span><span>Class: <b>${esc(st.klass||'')}</b></span><span>Total: <b>90 marks</b></span></div>`+body);}
function printKey(){const st=getState();if(!st||!st.questions?.length){alert('Complete or start an examination first.');return;}const rows=st.questions.map((q,i)=>{const user=st.answers?.[q.id]??'';const ok=String(user).trim().toLowerCase()===String(q.answer??'').trim().toLowerCase();return `<tr><td>${i+1}</td><td>${esc(q.answer||'')}</td><td>${q.marks}</td><td>${ok?'Correct':'Incorrect / blank'}</td></tr>`}).join('');page('APLUS P6 English Prelim — Answer Key',header('Answer Key','Paper 2')+`<table class="keytable"><tr><th>Q</th><th>Correct Answer</th><th>Marks</th><th>Student Result</th></tr>${rows}</table>`);}
function printTeacher(){const st=getState();if(!st||!st.questions?.length){alert('Complete or start an examination first.');return;}let earned=0,total=0;const rows=st.questions.map((q,i)=>{const u=st.answers?.[q.id]??'';const ok=String(u).trim().toLowerCase()===String(q.answer??'').trim().toLowerCase();if(ok)earned+=q.marks;total+=q.marks;return `<tr><td>${i+1}</td><td>${esc(q.sectionName)}</td><td>${esc(u||'—')}</td><td>${esc(q.answer||'')}</td><td>${ok?'✓':'✗'}</td><td>${q.marks}</td></tr>`}).join('');page('APLUS P6 English Prelim — Teacher Version',header('Teacher Version','Paper 2 — Marking Record')+`<div class="meta"><span>Candidate: <b>${esc(st.candidate||'Candidate')}</b></span><span>Score: <b>${earned}/${total}</b></span><span>Percentage: <b>${Math.round(earned/90*100)}%</b></span></div><table class="keytable"><tr><th>Q</th><th>Section</th><th>Student Answer</th><th>Correct Answer</th><th>Result</th><th>Marks</th></tr>${rows}</table>`);}
function install(){const result=document.getElementById('result');if(!result)return;const box=document.createElement('div');box.className='print-actions';box.innerHTML='<button type="button" id="printPaperBtn">PRINT COMPLETED PAPER</button><button type="button" id="printKeyBtn">PRINT ANSWER KEY</button><button type="button" id="printTeacherBtn">PRINT TEACHER VERSION</button>';result.querySelector('.result-actions')?.after(box);document.getElementById('printPaperBtn').onclick=printPaper;document.getElementById('printKeyBtn').onclick=printKey;document.getElementById('printTeacherBtn').onclick=printTeacher;}
window.APLUS_PRELIM_PRINT={install,printPaper,printKey,printTeacher};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();
