/* APLUS P6 English Prelim — Database-Driven Paper 2 Engine V5.1 */
(function(){
'use strict';
const KEY='APLUS_P6_PRELIM_SESSION_V2',COMPLETED='APLUS_P6_PRELIM_COMPLETED_V2',TOTAL_TIME=6600;
const BLUEPRINT=[
{id:'grammar',name:'BOOKLET A · Grammar',count:10,marks:10,booklet:'A',kind:'mcq'},
{id:'vocabulary',name:'BOOKLET A · Vocabulary',count:5,marks:5,booklet:'A',kind:'mcq'},
{id:'vocabularyCloze',name:'BOOKLET A · Vocabulary Cloze',count:5,marks:5,booklet:'A',kind:'mcq'},
{id:'visual',name:'BOOKLET A · Visual Text',count:5,marks:5,booklet:'A',kind:'mcq'},
{id:'grammarCloze',name:'BOOKLET B · Grammar Cloze',count:10,marks:10,booklet:'B',kind:'oe'},
{id:'editing',name:'BOOKLET B · Editing for Spelling and Grammar',count:10,marks:10,booklet:'B',kind:'oe'},
{id:'comprehensionCloze',name:'BOOKLET B · Comprehension Cloze',count:15,marks:15,booklet:'B',kind:'oe'},
{id:'synthesis',name:'BOOKLET B · Synthesis and Transformation',count:5,marks:10,booklet:'B',kind:'oe'},
{id:'comprehension',name:'BOOKLET B · Comprehension',count:10,marks:20,booklet:'B',kind:'oe'}];
let state={started:false,submitted:false,index:0,remaining:TOTAL_TIME,questions:[],answers:{},candidate:'',className:'',profile:'standard',paperId:''},timer=null;
const $=id=>document.getElementById(id),esc=s=>String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function getDB(name){let a=window[name];if(Array.isArray(a))return a;try{a=eval(name);return Array.isArray(a)?a:[]}catch(e){return[];}}
function seed(){let x=(Date.now()^Math.floor(Math.random()*0xffffffff))>>>0;return function(){x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967296;};}
function shuffle(a,r){a=a.slice();for(let i=a.length-1;i>0;i--){let j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function uniqueById(a){let m=new Map();a.forEach(x=>{if(x&&x.id)m.set(x.id,x)});return [...m.values()];}
function sources(){return{
grammar:uniqueById([].concat(getDB('APLUS_AI_DB_V1_GRAMMAR_P6_QUESTION_BANK'),getDB('APLUS_AI_DB_V1_GRAMMAR_P6_EXPANSION_BATCH02'),getDB('APLUS_AI_DB_V1_GRAMMAR_P6_EXPANSION_BATCH03'),getDB('APLUS_AI_DB_V1_GRAMMAR_P6_EXPANSION_BATCH04'),getDB('APLUS_AI_DB_V1_P6_PSLE_PAPER2_CORE_GRAMMAR_BATCH01'))),
vocab:uniqueById([].concat(getDB('APLUS_AI_DB_V1_P6_PSLE_PAPER2_MASTER_VOCABULARY_CONTENT_B03'),getDB('APLUS_AI_DB_V1_P6_PSLE_PAPER2_CORE_VOCABULARY_BATCH02'))),
ce:uniqueById([].concat(getDB('APLUS_AI_DB_V1_P6_CLOZE_EDITING_QUESTION_BANK'),getDB('APLUS_AI_DB_V1_P6_CLOZE_EDITING_EXPANSION_BATCH02'),getDB('APLUS_AI_DB_V1_P6_CLOZE_EDITING_EXPANSION_BATCH03'),getDB('APLUS_AI_DB_V1_P6_CLOZE_EDITING_EXPANSION_BATCH04'))),
synth:uniqueById(getDB('APLUS_AI_DB_V1_P6_SYNTHESIS_TRANSFORMATION_QUESTION_BANK')),
comp:uniqueById([].concat(getDB('APLUS_AI_DB_V1_P6_COMPREHENSION_QUESTION_BANK'),getDB('APLUS_AI_DB_V1_P6_COMPREHENSION_EXPANSION_BATCH02'))),
passages:uniqueById([].concat(getDB('APLUS_AI_DB_V1_P6_COMPREHENSION_PASSAGE_SETS_BATCH01'),getDB('APLUS_AI_DB_V1_P6_COMPREHENSION_PASSAGE_SETS_BATCH02'))),
visual:uniqueById(getDB('APLUS_AI_DB_V1_P6_PSLE_PAPER2_CORE_VISUAL_TEXT_DNA_BATCH01')),
editingDNA:uniqueById(getDB('APLUS_AI_DB_V1_P6_PSLE_PAPER2_MASTER_EDITING_DNA_B03'))
};}
function take(pool,n,r,profile){let p=pool.slice();if(profile==='hard')p=p.filter(x=>(Number(x.difficulty)||3)>=3);if(profile==='vocabularyIntensive')p=p.filter(x=>String(x.skill||'').toLowerCase().includes('vocab')||String(x.topic||'').toLowerCase().includes('vocab')).concat(p);if(profile==='grammarIntensive')p=p.filter(x=>String(x.skill||'').toLowerCase().includes('grammar')||String(x.topic||'').toLowerCase().includes('grammar')).concat(p);if(profile==='comprehensionIntensive')p=p.filter(x=>x.passage||String(x.skill||'').toLowerCase().includes('inference')).concat(p);return shuffle(p,r).slice(0,n);}
function addMeta(q,section,number){let s=BLUEPRINT.find(x=>x.id===section);q.number=number;q.id='Q'+number;q.booklet=s.booklet;q.section=section;q.sectionName=s.name;return q;}
function grammarQuestions(S,n,r){return take(S.grammar,n*3,r,state.profile).filter(q=>Array.isArray(q.options)&&q.answer).slice(0,n).map(q=>({type:'mcq',marks:1,question:q.question||q.text,options:q.options.slice(0,4),answer:q.answer,explanation:q.explanation||'',skill:q.skill||q.topic||'grammar',sourceDatabase:'P6 Grammar Database',sourceRecordId:q.id,difficulty:Number(q.difficulty)||3}));}
function vocabQuestions(S,n,r){let out=[];take(S.vocab,n*5,r,state.profile).forEach(q=>{if(out.length>=n||!q.word)return;let stem='Because '+(q.contextClue||'the situation required care')+', the person was being ___.';let candidates=[q.word,(q.antonyms||[])[0],S.vocab.find(x=>x.word&&x.word!==q.word)?.word,S.vocab.find(x=>x.word&&x.word!==q.word&&(q.antonyms||[]).indexOf(x.word)<0)?.word];let opts=shuffle([...new Set(candidates)].slice(0,4),r);if(opts.length===4)out.push({type:'mcq',marks:1,question:stem,options:opts,answer:q.word,explanation:q.definition||'',skill:'contextual word choice',sourceDatabase:'P6 Master Vocabulary',sourceRecordId:q.id,difficulty:Number(q.difficulty)||3});});return out;}
function vocabCloze(S,n,r){let out=[];take(S.vocab,n*5,r,state.profile).forEach(q=>{if(out.length>=n||!q.word)return;let others=shuffle(S.vocab.filter(x=>x.word&&x.word!==q.word),r).slice(0,3).map(x=>x.word);if(others.length<3)return;out.push({type:'mcq',marks:1,question:'Read the context. '+(q.contextClue||'The person acted carefully.')+' Which word best completes the meaning? ___',options:shuffle([q.word,...others],r),answer:q.word,explanation:q.definition||'',skill:'vocabulary in context',sourceDatabase:'P6 Master Vocabulary',sourceRecordId:q.id,difficulty:Number(q.difficulty)||3});});return out;}
function visualQuestions(S,n,r){let out=[];shuffle(S.visual,r).forEach(v=>{if(out.length>=n)return;let title=v.title||'School Information';let text=(Array.isArray(v.elements)?v.elements:[]).map(x=>x.replace(/_/g,' ')).join(' · ');out.push({type:'mcq',marks:1,visual:{title,text:text||'Read the information carefully.'},question:'What is the main skill needed to answer this visual-text question?',options:['Locate and interpret information in the visual text','Ignore dates and conditions','Guess without using evidence','Use information from outside the visual text'],answer:'Locate and interpret information in the visual text',explanation:'Visual-text questions depend on retrieving and interpreting information presented in the text.',skill:(v.skills||['retrieval'])[0],sourceDatabase:'P6 Visual Text DNA',sourceRecordId:v.id,difficulty:Number(v.difficulty)||3});});return out;}
function oeFromCloze(S,n,r,section){return take(S.ce.filter(x=>x.type==='cloze'),n*3,r,state.profile).filter(q=>q.answer).slice(0,n).map(q=>({type:'oe',marks:1,passage:q.text,question:'Fill in the blank with the most suitable word.',answer:q.answer,acceptedPatterns:[q.answer],explanation:q.explanation||'',skill:q.skill||'grammar',sourceDatabase:'P6 Cloze and Editing Database',sourceRecordId:q.id,difficulty:Number(q.difficulty)||3}));}
function editingQuestions(S,n,r){let out=shuffle(S.editingDNA,r).filter(q=>q.original&&q.corrected&&q.original!==q.corrected).slice(0,n).map(q=>({type:'oe',marks:1,passage:q.original,question:'Correct the error in the sentence. Write the corrected sentence.',answer:q.corrected,acceptedPatterns:[q.corrected],explanation:q.rule||'',skill:q.errorType||'editing',sourceDatabase:'P6 Editing DNA',sourceRecordId:q.id,difficulty:Number(q.difficulty)||3}));return out;}
function synthQuestions(S,n,r){return take(S.synth,n*4,r,state.profile).filter(q=>q.answer).slice(0,n).map(q=>({type:'oe',marks:2,question:q.question,answer:q.answer,acceptedPatterns:q.acceptedPatterns||[q.answer],explanation:q.explanation||'',skill:q.skill||'synthesis',sourceDatabase:'P6 Synthesis and Transformation Database',sourceRecordId:q.id,difficulty:Number(q.difficulty)||3}));}
function comprehensionQuestions(S,n,r){let out=[];shuffle(S.passages,r).forEach(p=>{let qs=Array.isArray(p.questions)?shuffle(p.questions,r):[];qs.forEach(q=>{if(out.length>=n||!q.answer)return;out.push({type:'oe',marks:2,passage:p.text||p.passage||'',question:q.question,answer:q.answer,acceptedPatterns:[q.answer],explanation:q.explanation||'',skill:q.skill||q.type||'comprehension',sourceDatabase:'P6 Comprehension Passage Sets',sourceRecordId:(p.passageId||p.id)+'::'+(q.id||out.length),difficulty:Number(q.difficulty)||3});});});if(out.length<n)S.comp.forEach(q=>{if(out.length>=n||!q.answer||!q.question||!q.passage)return;out.push({type:'oe',marks:2,passage:q.passage,question:q.question,answer:q.answer,acceptedPatterns:[q.answer],explanation:q.explanation||'',skill:q.skill||q.type||'comprehension',sourceDatabase:'P6 Comprehension Question Bank',sourceRecordId:q.id,difficulty:Number(q.difficulty)||3});});return out.slice(0,n);}
function build(r){let S=sources(),qs=[];function add(sec,arr){arr.slice(0,BLUEPRINT.find(x=>x.id===sec).count).forEach(q=>qs.push(addMeta(q,sec,qs.length+1)));}add('grammar',grammarQuestions(S,10,r));add('vocabulary',vocabQuestions(S,5,r));add('vocabularyCloze',vocabCloze(S,5,r));add('visual',visualQuestions(S,5,r));add('grammarCloze',oeFromCloze(S,10,r,'grammarCloze'));add('editing',editingQuestions(S,10,r));add('comprehensionCloze',oeFromCloze(S,15,r,'comprehensionCloze'));add('synthesis',synthQuestions(S,5,r));add('comprehension',comprehensionQuestions(S,10,r));return qs;}
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));if($(id))$(id).classList.add('active');}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch(e){}}
function load(){try{let x=JSON.parse(localStorage.getItem(KEY)||'null');if(x&&Array.isArray(x.questions)&&x.questions.length===75&&!x.submitted){state=x;return true;}}catch(e){}return false;}
function renderNav(){let box=$('sectionNav');if(!box)return;box.innerHTML='';BLUEPRINT.forEach(sec=>{let qs=state.questions.filter(q=>q.section===sec.id);let w=document.createElement('div');w.className='nav-section';w.innerHTML='<div class="nav-section-title">'+esc(sec.name.replace('BOOKLET A · ','').replace('BOOKLET B · ',''))+'</div><div class="nav-grid">'+qs.map(q=>'<button class="nav-q '+(q.number===state.index+1?'current ':'')+(state.answers[q.number]?'answered':'')+'" data-q="'+q.number+'">'+q.number+'</button>').join('')+'</div>';box.appendChild(w);});box.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>{state.index=+b.dataset.q-1;save();render();});}
function render(){let q=state.questions[state.index];if(!q)return;let sec=BLUEPRINT.find(s=>s.id===q.section);if($('bookletLabel'))$('bookletLabel').textContent='BOOKLET '+q.booklet;if($('sectionLabel'))$('sectionLabel').textContent=sec.name.replace(/^BOOKLET [AB] · /,'').toUpperCase();if($('progressText'))$('progressText').textContent='Question '+q.number+' of 75';if($('markText'))$('markText').textContent=q.marks+' mark'+(q.marks>1?'s':'');if($('progressBar'))$('progressBar').style.width=(q.number/75*100)+'%';let h='<div class="q-kicker">'+esc(q.sectionName)+'</div><div class="question-number">Question '+q.number+'</div>';if(q.visual)h+='<div class="visual-box"><h3>'+esc(q.visual.title)+'</h3><p>'+esc(q.visual.text)+'</p></div>';if(q.passage)h+='<div class="passage-box">'+esc(q.passage).replace(/\n/g,'<br>')+'</div>';h+='<div class="question-prompt">'+esc(q.question)+'</div>';if(q.type==='mcq')h+='<div class="options">'+q.options.map((o,i)=>'<label class="option"><input type="radio" name="answer" value="'+esc(o)+'" '+(state.answers[q.number]===o?'checked':'')+'><span class="option-letter">'+String.fromCharCode(65+i)+'.</span><span>'+esc(o)+'</span></label>').join('')+'</div>';else h+='<input id="oeAnswer" class="oe-answer" type="text" autocomplete="off" value="'+esc(state.answers[q.number]||'')+'" placeholder="Type your answer here">';$('questionCard').innerHTML=h;if(q.type==='mcq')document.querySelectorAll('input[name="answer"]').forEach(x=>x.onchange=()=>{state.answers[q.number]=x.value;save();renderNav();});else if($('oeAnswer'))$('oeAnswer').oninput=e=>{state.answers[q.number]=e.target.value;save();renderNav();};renderNav();}
function start(){let r=seed();state={started:true,submitted:false,index:0,remaining:TOTAL_TIME,questions:build(r),answers:{},candidate:$('candidateName')?.value.trim()||'',className:$('candidateClass')?.value.trim()||'',profile:$('paperProfile')?.value||'standard',paperId:'APLUS-P6-ENG-P2-'+new Date().toISOString().slice(0,10).replace(/-/g,'')+'-'+Math.floor(r()*900000+100000)};if(state.questions.length!==75){alert('Database generation returned '+state.questions.length+' questions. Please refresh the page.');return;}save();show('exam');render();runTimer();}
function runTimer(){clearInterval(timer);timer=setInterval(()=>{if(state.submitted)return;state.remaining--;if(state.remaining<0)state.remaining=0;let h=Math.floor(state.remaining/3600),m=Math.floor(state.remaining%3600/60),s=state.remaining%60;if($('timer'))$('timer').textContent=[h,m,s].map(x=>String(x).padStart(2,'0')).join(':');if(state.remaining%10===0)save();if(state.remaining===0)submit();},1000);}
function norm(x){return String(x==null?'':x).toLowerCase().replace(/[.!?,;:'"“”‘’()\[\]{}]/g,' ').replace(/\s+/g,' ').trim();}
function check(q,a){if(!a)return false;let x=norm(a),p=(q.acceptedPatterns||[q.answer||'']).map(norm);return p.some(v=>x===v);}
function submit(){if(state.submitted)return;clearInterval(timer);state.submitted=true;state.score=state.questions.reduce((n,q)=>n+(check(q,state.answers[q.number])?q.marks:0),0);state.percentage=Math.round(state.score/90*100);try{localStorage.setItem(COMPLETED,JSON.stringify(state));localStorage.removeItem(KEY);}catch(e){}show('result');renderResult();}
function renderResult(){if($('paperId'))$('paperId').textContent=state.paperId;if($('score'))$('score').textContent=state.score+' / 90';if($('percentage'))$('percentage').textContent=state.percentage+'%';if($('resultMessage'))$('resultMessage').textContent=state.percentage>=80?'Strong progress':state.percentage>=50?'More practice needed':'Let’s rebuild the basics';let by={};state.questions.forEach(q=>{by[q.sectionName]=by[q.sectionName]||{score:0,max:0};by[q.sectionName].max+=q.marks;if(check(q,state.answers[q.number]))by[q.sectionName].score+=q.marks;});if($('sectionResults'))$('sectionResults').innerHTML=Object.entries(by).map(([k,v])=>'<div class="result-row"><span>'+esc(k)+'</span><strong>'+v.score+' / '+v.max+'</strong></div>').join('');}
function bind(){if($('startBtn'))$('startBtn').onclick=start;if($('confirmSubmitBtn'))$('confirmSubmitBtn').onclick=submit;if($('backToExamBtn'))$('backToExamBtn').onclick=()=>{show('exam');render();runTimer();};if($('prevBtn'))$('prevBtn').onclick=()=>{if(state.index>0){state.index--;save();render();}};if($('nextBtn'))$('nextBtn').onclick=()=>{if(state.index<74){state.index++;save();render();}else{let n=state.questions.filter(q=>!state.answers[q.number]).length;if($('submitSummary'))$('submitSummary').innerHTML='<p>You have '+n+' unanswered question(s).</p>';show('submitScreen');}};if($('reviewBtn'))$('reviewBtn').onclick=()=>{show('exam');render();};if($('printBtn'))$('printBtn').onclick=()=>window.print();if($('newExamBtn'))$('newExamBtn').onclick=()=>{localStorage.removeItem(KEY);localStorage.removeItem(COMPLETED);location.reload();};if(load()){show('exam');render();runTimer();}}
window.APLUS_P6_PRELIM_V5={BLUEPRINT,start,buildQuestions:build,getState:()=>state,sourceSummary:()=>{let s=sources();return Object.fromEntries(Object.entries(s).map(([k,v])=>[k,v.length]));}};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();